### ISSUE TITLE
[BUG] Will not install

### ISSUE THREAD

**Issue by mrhappyma** [urmomjs/urmom.js#2]
**Describe the bug**
Package will not install
I can get the errors later not at a machine with node atm

**To Reproduce**
1. Run `npm i urmom.js` or `pnpm add urmom.js`

**Expected behavior**
It installs

**Additional context**
It's been about a month since I tried just rememberd to make an issue now

**Comment by macedonga** [comment]
It installs on my machine:
![image](https://user-images.githubusercontent.com/19750900/159125557-6f75ca55-8623-44dc-94f9-12b2ac43cdde.png)

**Comment by jdev082** [comment]
@mrhappyma I too have build errors, but they are related to node-gyp and not urmomjs itself. Are you too getting node-gyp build errors?

**Comment by mrhappyma** [comment]
woah, i forgot about this issue...
just gave it a shot. `pnpm` yelled about peer dependencies. `npm` was slow but fine.

new year new me, issue closed :+1:
